### ISSUE TITLE
Modo Egresado

### ISSUE THREAD

**Issue by ericmguzmanc** [ericmguzmanc/egresados-uasd#37]
### Details

Queremos permitir a un usuario con role `Egresado` pueda editar su perfil.

### Acceptance Criteria
- Cuándo ves el detalle de tu usuario vez el botón de edición a tu derecha al inicio de la página para editar dicho usuario.

**Comment by elizonRL** [comment]
pudiésemos cambiar lo de ir al detalle y ver el lapicito ?
