### ISSUE TITLE
Egresados List - Imagen de perfil muy pequeña

### ISSUE THREAD

**Issue by elizonRL** [ericmguzmanc/egresados-uasd#60]
### Detalles

Queremos que la imagen de perfil que se ve en la lista no se vea muy pequeña.

### Criterios de Aceptación

1. La imagen de perfil en el componente `egresados-list` se ve más grande

**Comment by ericmguzmanc** [comment]
Información útil: Me parece que se debe a que hay mucha información que se está mostrando en el item, si removemos una línea y cambiamos el tamaño de fuete a empresa, podría verse más grande.

**Comment by elizonRL** [comment]
Ok, cuando trabaje con el hare algunas pruebas

**Comment by ericmguzmanc** [comment]
Me parece que con los cambios en el PR #54 ya este ticket no será necesario
